services:
  postgres:
    image: postgres:17-alpine
    container_name: as_stats_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_OZI_PASSWORD: ${POSTGRES_OZI_PASSWORD:-ozi_password}
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - ./create_database_schema.sql:/docker-entrypoint-initdb.d/create_database_schema.sql:ro
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-ozi_db2}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ozi_network

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: as_stats_etl
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-ozi_db2}
      DB_USER: ${POSTGRES_OZI_USER:-ozi}
      DB_PASS: ${POSTGRES_OZI_PASSWORD:-password}
      OZI_DATABASE_HOST:     postgres
      OZI_DATABASE_PORT:     5432
      OZI_DATABASE_NAME:     ${POSTGRES_DB:-ozi_db2}
      OZI_DATABASE_USER:     ${POSTGRES_OZI_USER:-ozi}
      OZI_DATABASE_PASSWORD: ${POSTGRES_OZI_PASSWORD:-password}
    volumes:
      - ./etl/logs:/app/etl/logs
    networks:
      - ozi_network

  redash-server:
    image: redash/redash:25.1.0
    profiles:
      - redash
    command: server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET:-secret}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY:-secret}
      REDASH_REDIS_URL: redis://redash-redis:6379/0
      REDASH_LOG_LEVEL: INFO
      REDASH_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres/postgres
    depends_on:
      - postgres
      - redash-redis
    restart: unless-stopped
    networks:
      - ozi_network

  redash-worker:
    image: redash/redash:25.1.0
    profiles:
      - redash
    command: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redash-redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres/postgres
    depends_on:
      - postgres
      - redash-redis
    restart: unless-stopped
    networks:
      - ozi_network

  redash-redis:
    image: redis:7.0-alpine
    profiles:
      - redash
    restart: unless-stopped
    networks:
      - ozi_network

volumes:
  pgdata:

networks:
  ozi_network:
    driver: bridge